USE master
GO

IF DB_ID('21BI11_METADATA') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_METADATA]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_METADATA]
END
GO

CREATE DATABASE [21BI11_METADATA]
GO
USE [21BI11_METADATA]
GO

CREATE TABLE STAGE (
    ID INT IDENTITY,
    TABNAME VARCHAR(50),
    LSET DATETIME,

    CONSTRAINT PK_STAGE
    PRIMARY KEY(ID)
)

CREATE TABLE NDS (
    ID INT IDENTITY,
    TABNAME VARCHAR(50),
    LSET DATETIME,

    CONSTRAINT PK_NDS
    PRIMARY KEY(ID)
)

CREATE TABLE DDS (
    ID INT IDENTITY,
    TABNAME VARCHAR(50),
    LSET DATETIME,

    CONSTRAINT PK_DDS
    PRIMARY KEY(ID)
)

CREATE TABLE SRC_SYS (
    ID INT IDENTITY,
    [NAME] NVARCHAR(150),
    [FILE] NVARCHAR(150),

    CONSTRAINT PK_SRC_SYS
    PRIMARY KEY(ID)
)

CREATE TABLE SCD_STATUS (
    ID INT IDENTITY(0, 1),
    [NAME] NVARCHAR(50),

    CONSTRAINT PK_SCD_STATUS
    PRIMARY KEY(ID)
)
GO

INSERT INTO SRC_SYS VALUES
    ('AIR QUALITY 2021', '10_state_aqi_2021.csv'),
    ('AIR QUALITY 2022', '10_state_aqi_2022.csv'),
    ('AIR QUALITY 2023', '10_state_aqi_2023.csv'),
    ('US COUNTIES', '(2B)uscounties.csv'),
    ('CLEANING STAGE DATA', '3_clean_data.sql')

INSERT INTO SCD_STATUS VALUES('INACTIVE'), ('ACTIVE')

GO