USE master
GO

IF DB_ID('21BI11_STAGE') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_STAGE]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_STAGE]
END
GO

CREATE DATABASE [21BI11_STAGE]
GO
USE [21BI11_STAGE]
GO

CREATE TABLE [10_STATE_AQI] (
    STATE_NAME NVARCHAR(150),
    COUNTY_NAME NVARCHAR(150),
    STATE_CODE INT,
    COUNTY_CODE INT,
    [DATE] NVARCHAR(50),
    AQI INT,
    CATEGORY NVARCHAR(50),
    DEFINING_PARAMETER NVARCHAR(50),
    DEFINING_SITE NVARCHAR(50),
    NUMBER_OF_SITES_REPORTING INT,
    CREATED DATETIME,
    LAST_UPDATED DATETIME,
    SOURCE_ID INT
)

CREATE TABLE [2B_USCOUNTIES] (
    COUNTY NVARCHAR(150),
    COUNTY_ASCII NVARCHAR(150),
    COUNTY_FULL NVARCHAR(150),
    COUNTY_FIPS NVARCHAR(5),
    STATE_ID NVARCHAR(2),
    STATE_NAME NVARCHAR(150),
    LAT FLOAT,
    LNG FLOAT,
    [POPULATION] INT,
    CREATED DATETIME,
    LAST_UPDATED DATETIME,
    SOURCE_ID INT
)
GO

TRUNCATE TABLE [21BI11_METADATA].dbo.STAGE

INSERT INTO [21BI11_METADATA].dbo.STAGE
    SELECT TABLE_NAME, '2000-01-01 00:00:00.000'
    FROM [21BI11_STAGE].INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE='BASE TABLE'

GO