USE master
GO

IF DB_ID('21BI11_NDS') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_NDS]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_NDS]
END
GO

CREATE DATABASE [21BI11_NDS]
GO
USE [21BI11_NDS]
GO

CREATE TABLE [STATE] (
    STATE_ID_SK INT IDENTITY,
    STATE_ID NVARCHAR(2),
    STATE_NAME NVARCHAR(150),
    CREATED DATETIME,
    LAST_UPDATED DATETIME,
    SOURCE_ID INT,

    CONSTRAINT PK_STATE
    PRIMARY KEY(STATE_ID_SK)
)

CREATE TABLE [COUNTY] (
    COUNTY_ID INT IDENTITY,
    COUNTY NVARCHAR(150),
    COUNTY_FIPS NVARCHAR(5),
    STATE_ID_SK INT,
    [POPULATION] INT,
    LAT FLOAT,
    LNG FLOAT,
    CREATED DATETIME,
    LAST_UPDATED DATETIME,
    SOURCE_ID INT,

    CONSTRAINT PK_COUNTY
    PRIMARY KEY(COUNTY_ID),

    CONSTRAINT FK_COUNTY_STATE
    FOREIGN KEY(STATE_ID_SK) REFERENCES [STATE](STATE_ID_SK)
)

CREATE TABLE [AIR_QUALITY] (
    AQI_ID INT IDENTITY,
    COUNTY_ID INT,
    [DATE] DATE,
    AQI INT,
    CATEGORY NVARCHAR(50),
    DEFINING_PARAMETER NVARCHAR(50),
    DEFINING_SITE NVARCHAR(50),
    NUMBER_OF_SITES_REPORTING INT,
    CREATED DATETIME,
    LAST_UPDATED DATETIME,
    SOURCE_ID INT,

    CONSTRAINT PK_AIR_QUALITY
    PRIMARY KEY(AQI_ID),

    CONSTRAINT FK_AIR_QUALITY_COUNTY
    FOREIGN KEY(COUNTY_ID) REFERENCES COUNTY(COUNTY_ID)
)
GO

TRUNCATE TABLE [21BI11_METADATA].dbo.NDS

INSERT INTO [21BI11_METADATA].dbo.NDS
    SELECT TABLE_NAME, '2000-01-01 00:00:00.000'
    FROM [21BI11_NDS].INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE='BASE TABLE'

GO