USE [21BI11_DDS]
GO

DROP TABLE IF EXISTS dbo.[MINING_AIR_QUALITY]

CREATE TABLE [MINING_AIR_QUALITY] (
    AQI_ID INT,
    GEO_ID INT,
    DATE_ID INT,
    AQI INT,
    CATEGORY NVARCHAR(50),
    DEFINING_PARAMETER NVARCHAR(50),
    DEFINING_SITE NVARCHAR(50),
    NUMBER_OF_SITES_REPORTING INT,
	STATE_NAME NVARCHAR(150),
    COUNTY NVARCHAR(150),
	[YEAR] INT,
    [QUARTER] INT,
    [MONTH] INT,
    [DAY] INT,

    CONSTRAINT PK_MINING_AIR_QUALITY
    PRIMARY KEY(AQI_ID),
)
GO

INSERT INTO MINING_AIR_QUALITY
    SELECT
        AQI_ID,
        GEO_ID,
        DATE_ID,
        AQI,
        CATEGORY,
        DEFINING_PARAMETER,
        DEFINING_SITE,
        NUMBER_OF_SITES_REPORTING,
        'PLACEHOLDER' AS STATE_NAME,
        'PLACEHOLDER' AS COUNTY,
        0 AS [YEAR],
        0 AS [QUARTER],
        0 AS [MONTH],
        0 AS [DAY]
    FROM dbo.FACT_AIR_QUALITY
GO

MERGE INTO [MINING_AIR_QUALITY] MI
    USING [DIM_GEO] GE ON MI.GEO_ID=GE.GEO_ID
WHEN MATCHED THEN
    UPDATE SET MI.STATE_NAME=GE.STATE_NAME, MI.COUNTY=GE.COUNTY;

MERGE INTO [MINING_AIR_QUALITY] MI
    USING [DIM_DATE] DA ON MI.DATE_ID=DA.DATE_ID
WHEN MATCHED THEN
    UPDATE SET MI.[YEAR]=DA.[YEAR], MI.[QUARTER]=DA.[QUARTER],
               MI.[MONTH]=DA.[MONTH], MI.[DAY]=DA.[DAY];
GO