USE master
GO

IF DB_ID('21BI11_METADATA') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_METADATA]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_METADATA]
END
GO

CREATE DATABASE [21BI11_METADATA]
GO
USE [21BI11_METADATA]
GO

CREATE TABLE STAGE (
    ID INT IDENTITY,
    TABNAME VARCHAR(50),
    LSET DATETIME,

    CONSTRAINT PK_STAGE
    PRIMARY KEY(ID)
)

GO