USE master
GO

IF DB_ID('21BI11_METADATA') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_METADATA]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_METADATA]
END
GO

IF DB_ID('21BI11_STAGE') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_STAGE]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_STAGE]
END
GO

IF DB_ID('21BI11_NDS') IS NOT NULL
BEGIN
    ALTER DATABASE [21BI11_NDS]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [21BI11_NDS]
END
GO